### ISSUE TITLE
Error during npm start

### ISSUE THREAD

**Issue by thardes2** [mgechev/electron-typescript-boilerplate#1]
By running the how to, `npm start` gives the following error:
![image](https://user-images.githubusercontent.com/6141477/27640499-c926931e-5c19-11e7-96cc-46edc180a202.png)

**Comment by adamnemecek** [comment]
Have the same issue.

**Comment by schnesim** [comment]
yep, me too

**Comment by adamnemecek** [comment]
Check out electron forge. I actually kinda made things work

https://github.com/electron-userland/electron-forge

**Comment by schnesim** [comment]
I found a couple of workarounds:
a) In the project root execute this command 
`cp node_modules/electron/electron.d.ts node_modules/@types/electron/index.d.ts`
OR
b) Replace the electron "import" statements with their "require" equivalent.

**Comment by robdmoore** [comment]
I also got this problem and it seems to be fixed after adding this to `compilerOptions` in `tsconfig.json`: `"moduleResolution": "node",`

**Comment by arvin-a** [comment]
Yup "moduleResolution": "node" in tsconfig solved the problem
